import React, { useState } from 'react';
import { 
  Camera, 
  RotateCcw, 
  Share2, 
  Download, 
  Copy, 
  Check, 
  Layers, 
  Plus, 
  Trash2, 
  FileCode, 
  CheckCircle2, 
  Users,
  Code,
  Sparkles
} from 'lucide-react';
import { FileNode, PreflightConfig, ServiceInfo, SessionSnapshot } from '../../types';

interface SnapshotsAndCollabProps {
  nodes: FileNode[];
  services: ServiceInfo[];
  snapshots: SessionSnapshot[];
  onCreateSnapshot: (name: string, note?: string) => void;
  onRestoreSnapshot: (snapshotId: string) => void;
  onDeleteSnapshot: (snapshotId: string) => void;
  preflightConfig: PreflightConfig;
  onLoadStackPreset: (presetId: string) => void;
  onAddLog: (category: 'runtime' | 'build' | 'analysis' | 'terminal', level: 'info' | 'warn' | 'error' | 'success', msg: string) => void;
}

const READY_STACKS = [
  { id: 'mern-postgres', name: 'React + Node + PostgreSQL', desc: 'تطبيق ويب متكامل مع قاعدة بيانات علائقية ومحاكي API', icon: '🚀' },
  { id: 'next-fullstack', name: 'Next.js 14 App Router', desc: 'واجهة أمامية + مسارات خادم Server Components مدمجة', icon: '⚡' },
  { id: 'fastapi-mongo', name: 'Python FastAPI + MongoDB', desc: 'خادم بايثون غير متزامن مع قاعدة وثائق NoSQL وسكربتات pytest', icon: '🐍' },
  { id: 'go-redis', name: 'Go Fiber + Redis Cache', desc: 'خدمة دقيقة فائقة السرعة مع تخزين مؤقت سريع ومراقبة حية', icon: '🏎️' },
  { id: 'rust-axum', name: 'Rust Axum High-Perf API', desc: 'أمان الذاكرة وأقصى كفاءة استهلاك للموارد', icon: '🦀' },
  { id: 'dotnet-api', name: '.NET 8 Web API', desc: 'بنية مؤسسات متينة مع Swagger/OpenAPI مدمج', icon: '🔷' },
  { id: 'react-native-expo', name: 'React Native / Expo Mobile', desc: 'تطبيق هاتف مع Metro Bundler ومحاكي أجهزة ومعاينة QR', icon: '📱' },
];

export const SnapshotsAndCollab: React.FC<SnapshotsAndCollabProps> = ({
  nodes,
  services,
  snapshots,
  onCreateSnapshot,
  onRestoreSnapshot,
  onDeleteSnapshot,
  preflightConfig,
  onLoadStackPreset,
  onAddLog
}) => {
  const [snapshotName, setSnapshotName] = useState('');
  const [snapshotNote, setSnapshotNote] = useState('');
  const [shareLinkRole, setShareLinkRole] = useState<'view' | 'interactive'>('view');
  const [copiedShareLink, setCopiedShareLink] = useState(false);
  const [copiedDockerCompose, setCopiedDockerCompose] = useState(false);

  const shareUrl = `${window.location.origin}${window.location.pathname}?session_collab=${Date.now()}&mode=${shareLinkRole}#collab-live`;

  const handleTakeSnapshot = () => {
    if (!snapshotName.trim()) return;
    onCreateSnapshot(snapshotName.trim(), snapshotNote.trim());
    setSnapshotName('');
    setSnapshotNote('');
  };

  const handleCopyShareLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopiedShareLink(true);
    setTimeout(() => setCopiedShareLink(false), 2000);
    onAddLog('runtime', 'info', `[تعاون] تم توليد ونسخ رابط مشاركة الجلسة (الوضع: ${shareLinkRole})`);
  };

  // Generate docker-compose.yml
  const generateDockerComposeYaml = (): string => {
    return `version: '3.8'

services:
  frontend:
    image: node:20-alpine
    container_name: app_frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=3000
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    image: node:20-alpine
    container_name: app_backend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    command: node server.js
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:secret@postgres:5432/app_db
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_password_local
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
`;
  };

  // Generate run.sh
  const generateRunSh = (): string => {
    return `#!/usr/bin/env bash
# Quick local run script generated by Web App Studio
set -e

echo "🚀 إقلاع المشروع محلياً بواسطة Docker Compose..."
if command -v docker-compose &> /dev/null; then
  docker-compose up -d --build
else
  docker compose up -d --build
fi

echo "✅ تم تشغيل الحاويات بنجاح!"
echo "🌐 الواجهة الأمامية: http://localhost:3000"
echo "⚙️ الخادم والـ API: http://localhost:8080"
echo "🐘 قاعدة البيانات: localhost:5432"
`;
  };

  const handleDownloadLocalPackage = () => {
    // Trigger download of docker-compose.yml
    const blob = new Blob([generateDockerComposeYaml()], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'docker-compose.yml';
    a.click();
    URL.revokeObjectURL(url);

    // Trigger download of run.sh
    const shBlob = new Blob([generateRunSh()], { type: 'text/x-sh' });
    const shUrl = URL.createObjectURL(shBlob);
    const a2 = document.createElement('a');
    a2.href = shUrl;
    a2.download = 'run.sh';
    a2.click();
    URL.revokeObjectURL(shUrl);

    onAddLog('runtime', 'success', 'تم توليد وتنزيل ملفات التشغيل المحلي (docker-compose.yml و run.sh) بنجاح.');
  };

  return (
    <div className="bg-[#0b1120] border border-[#334155] rounded-[8px] p-4 space-y-4">
      {/* Ready Stack Presets (قوالب بيئات جاهزة) */}
      <div className="bg-[#080d1a] p-3.5 rounded-[6px] border border-[#334155] space-y-2.5">
        <div className="flex items-center justify-between pb-1.5 border-b border-[#334155]">
          <span className="text-xs font-bold text-white flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-[#f59e0b]" />
            <span>قوالب بيئات جاهزة معمارياً (Ready Stack Presets)</span>
          </span>
          <span className="text-[11px] text-[#94a3b8]">تبديل فوري لتوليد الإعدادات الموصى بها</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-xs">
          {READY_STACKS.map(stack => (
            <button
              key={stack.id}
              type="button"
              onClick={() => onLoadStackPreset(stack.id)}
              className="bg-[#0b1120] hover:bg-[#1e293b] p-2.5 rounded border border-[#334155] hover:border-[#38bdf8]/50 text-right transition cursor-pointer flex flex-col justify-between group"
            >
              <div>
                <div className="font-bold text-white flex items-center gap-1.5 group-hover:text-[#38bdf8]">
                  <span>{stack.icon}</span>
                  <span>{stack.name}</span>
                </div>
                <p className="text-[11px] text-[#94a3b8] mt-1 leading-relaxed">{stack.desc}</p>
              </div>
              <span className="text-[10px] text-[#38bdf8] mt-2 font-mono">تطبيق القالب ←</span>
            </button>
          ))}
        </div>
      </div>

      {/* Snapshots & Session State Recovery */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Left: Take Snapshot */}
        <div className="bg-[#080d1a] p-3.5 rounded-[6px] border border-[#334155] space-y-3 text-xs">
          <div className="flex items-center justify-between pb-1.5 border-b border-[#334155]">
            <span className="font-bold text-white flex items-center gap-1.5">
              <Camera className="w-4 h-4 text-[#38bdf8]" />
              <span>أخذ لقطة للجلسة (Save Snapshot)</span>
            </span>
            <span className="text-[11px] text-[#94a3b8]">لتكرار الأخطاء ومقارنة التعديلات</span>
          </div>

          <div className="space-y-2">
            <input
              type="text"
              value={snapshotName}
              onChange={(e) => setSnapshotName(e.target.value)}
              placeholder="اسم اللقطة (مثال: قبل تعديل قواعد البيانات)..."
              className="w-full bg-[#0b1120] text-white p-2 rounded border border-[#334155] outline-none text-xs"
            />
            <input
              type="text"
              value={snapshotNote}
              onChange={(e) => setSnapshotNote(e.target.value)}
              placeholder="ملاحظات توثيقية (اختياري)..."
              className="w-full bg-[#0b1120] text-slate-300 p-2 rounded border border-[#334155] outline-none text-xs"
            />
            <button
              type="button"
              onClick={handleTakeSnapshot}
              disabled={!snapshotName.trim()}
              className="w-full py-2 bg-[#3b82f6] hover:bg-blue-600 text-white font-bold rounded text-xs flex items-center justify-center gap-1.5 cursor-pointer disabled:opacity-40 transition"
            >
              <Camera className="w-3.5 h-3.5" />
              <span>حفظ لقطة جديدة (Take Snapshot)</span>
            </button>
          </div>

          {/* Snapshots List */}
          <div className="space-y-1.5 max-h-40 overflow-y-auto pt-2 border-t border-[#334155]">
            <span className="text-[11px] text-[#94a3b8] block">اللقطات المحفوظة ({snapshots.length}):</span>
            {snapshots.length === 0 ? (
              <div className="text-[#94a3b8]/50 py-3 text-center text-xs">لا توجد لقطات محفوظة حتى الآن.</div>
            ) : (
              snapshots.map(sn => (
                <div key={sn.id} className="bg-[#0b1120] p-2 rounded border border-[#334155] flex items-center justify-between">
                  <div>
                    <div className="font-bold text-white">{sn.name}</div>
                    <div className="text-[10px] text-[#94a3b8] font-mono flex items-center gap-1.5">
                      <span>{sn.createdAt}</span>
                      <span>•</span>
                      <span>{sn.filesCount} ملف</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <button
                      type="button"
                      onClick={() => onRestoreSnapshot(sn.id)}
                      className="px-2 py-1 bg-[#10b981] hover:bg-emerald-600 text-white rounded text-[11px] flex items-center gap-1 cursor-pointer"
                      title="استرجاع حالة الجلسة"
                    >
                      <RotateCcw className="w-3 h-3" />
                      <span>استرجاع</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => onDeleteSnapshot(sn.id)}
                      className="p-1 text-[#94a3b8] hover:text-rose-400 cursor-pointer"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Right: Real-time Collab & Local Export */}
        <div className="space-y-4">
          {/* Real-time Collaboration Share */}
          <div className="bg-[#080d1a] p-3.5 rounded-[6px] border border-[#334155] space-y-2.5 text-xs">
            <div className="flex items-center justify-between pb-1.5 border-b border-[#334155]">
              <span className="font-bold text-white flex items-center gap-1.5">
                <Users className="w-4 h-4 text-[#10b981]" />
                <span>مشاركة الجلسة في الوقت الحقيقي (Live Session Sharing)</span>
              </span>
              <span className="text-[10px] text-[#10b981] font-mono">جلسة مشفرة</span>
            </div>

            <div className="flex items-center gap-2">
              <span className="text-[#94a3b8] text-[11px]">صلاحية المشارك:</span>
              <label className="flex items-center gap-1 text-slate-200 cursor-pointer">
                <input
                  type="radio"
                  name="role"
                  checked={shareLinkRole === 'view'}
                  onChange={() => setShareLinkRole('view')}
                  className="accent-[#3b82f6]"
                />
                <span>معاينة فقط (View-only)</span>
              </label>
              <label className="flex items-center gap-1 text-slate-200 cursor-pointer">
                <input
                  type="radio"
                  name="role"
                  checked={shareLinkRole === 'interactive'}
                  onChange={() => setShareLinkRole('interactive')}
                  className="accent-[#3b82f6]"
                />
                <span>تفاعلي كامل (Interactive)</span>
              </label>
            </div>

            <div className="flex items-center gap-2 bg-[#0b1120] p-2 rounded border border-[#334155] font-mono text-[11px] text-[#38bdf8] truncate" dir="ltr">
              <span className="flex-1 truncate">{shareUrl}</span>
              <button
                type="button"
                onClick={handleCopyShareLink}
                className="px-2 py-1 bg-[#1e293b] hover:bg-[#334155] text-white rounded cursor-pointer flex items-center gap-1 shrink-0"
              >
                {copiedShareLink ? <Check className="w-3 h-3 text-[#10b981]" /> : <Copy className="w-3 h-3" />}
                <span>{copiedShareLink ? 'تم النسخ' : 'نسخ الرابط'}</span>
              </button>
            </div>
          </div>

          {/* Local Docker Compose & Run.sh Generator */}
          <div className="bg-[#080d1a] p-3.5 rounded-[6px] border border-[#334155] space-y-2.5 text-xs">
            <div className="flex items-center justify-between pb-1.5 border-b border-[#334155]">
              <span className="font-bold text-white flex items-center gap-1.5">
                <Download className="w-4 h-4 text-[#38bdf8]" />
                <span>حزمة التشغيل المحلي (docker-compose.yml + run.sh)</span>
              </span>
              <span className="text-[10px] text-[#94a3b8]">التشغيل الذاتي خارج المتصفح</span>
            </div>

            <p className="text-[11px] text-[#94a3b8] leading-relaxed">
              قم بتوليد وتنزيل ملفات Docker الجاهزة لتشغيل نفس المشروع محلياً على حاسوبك بنفس إعدادات البيئة والمنافذ المحددة بنقرة واحدة.
            </p>

            <button
              type="button"
              onClick={handleDownloadLocalPackage}
              className="w-full py-2 bg-[#10b981] hover:bg-emerald-600 text-white font-bold rounded text-xs flex items-center justify-center gap-2 cursor-pointer transition shadow-sm"
            >
              <Download className="w-4 h-4" />
              <span>تنزيل docker-compose.yml و run.sh</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
