import { FileNode } from '../types';
import { DEFAULT_HTML_APP_TEMPLATE } from './defaultHtmlTemplate';
import { findRealisticContentForFile } from './sampleProjects';

/**
 * Generates an initial realistic code template for common file names.
 */
export function getDefaultContentForFile(fileName: string, fullPath?: string): string {
  if (fullPath) {
    const realistic = findRealisticContentForFile(fullPath);
    if (realistic) return realistic;
  }
  const realisticByName = findRealisticContentForFile(fileName);
  if (realisticByName) return realisticByName;

  const lower = fileName.toLowerCase();
  
  if (lower === 'index.html' || lower.endsWith('.html') || lower.endsWith('.htm')) {
    return DEFAULT_HTML_APP_TEMPLATE;
  }

  if (lower === 'package.json') {
    return `{
  "name": "my-awesome-project",
  "version": "1.0.0",
  "description": "Generated by Code Project Builder",
  "main": "src/index.js",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "start": "node src/index.js",
    "test": "echo \\"Error: no test specified\\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {
    "vite": "^5.0.0"
  }
}`;
  }

  if (lower === 'manifest.json') {
    return `{
  "name": "تطبيق ويب تقدمي PWA",
  "short_name": "تطبيقي",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#0f172a",
  "theme_color": "#6366f1",
  "description": "تطبيق ويب يدعم العمل دون اتصال وقابل للتثبيت كـ PWA",
  "icons": [
    {
      "src": "/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}`;
  }

  if (lower === 'sw.js' || lower === 'service-worker.js') {
    return `// Service Worker - Offline Cache
const CACHE_NAME = 'app-cache-v1';
const ASSETS_TO_CACHE = [
  '/',
  '/index.html',
  '/style.css',
  '/main.js',
  '/manifest.json'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[SW] Pre-caching offline assets');
      return cache.addAll(ASSETS_TO_CACHE);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) {
            console.log('[SW] Removing old cache', key);
            return caches.delete(key);
          }
        })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      return cachedResponse || fetch(event.request).catch(() => {
        return caches.match('/index.html');
      });
    })
  );
});`;
  }

  if (lower.endsWith('.css')) {
    return `/* أنماط المشروع العامة */
body {
  margin: 0;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background-color: #0f172a;
  color: #f8fafc;
}

.card {
  transition: transform 0.2s ease;
}

.card:hover {
  transform: translateY(-2px);
}`;
  }

  if (lower === 'main.js' || lower === 'index.js' || lower === 'app.js') {
    return `// نقطة الدخول الرئيسية
document.addEventListener('DOMContentLoaded', () => {
  console.log('تم تحميل التطبيق بنجاح!');
  const btn = document.getElementById('btn');
  if (btn) {
    btn.addEventListener('click', () => {
      alert('مرحباً بك! يعمل المشروع بتفاعل كامل.');
      console.log('User interacted with the button.');
    });
  }
});`;
  }

  if (lower === 'app.tsx' || lower === 'app.jsx') {
    return `import React, { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen bg-slate-900 text-white flex flex-col items-center justify-center p-6">
      <div className="bg-slate-800 p-8 rounded-2xl shadow-xl border border-slate-700 text-center max-w-md w-full">
        <h1 className="text-3xl font-bold text-indigo-400 mb-2">React Application</h1>
        <p className="text-slate-400 mb-6">مكون رئيسي تم إنشاؤه عبر استوديو المشاريع</p>
        <div className="flex items-center justify-center gap-4">
          <button 
            onClick={() => setCount(c => c + 1)}
            className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 rounded-lg font-medium transition"
          >
            العداد: {count}
          </button>
        </div>
      </div>
    </div>
  );
}`;
  }

  if (lower === 'main.py' || lower === 'app.py') {
    return `"""
نقطة انطلاق تطبيق بايثون
"""
import sys

def main():
    print("بدء تشغيل خادم Python...")
    print(f"إصدار بايثون: {sys.version}")
    
if __name__ == "__main__":
    main()
`;
  }

  if (lower === 'dockerfile') {
    return `# استخدام صورة Node الرسمية كقاعدة
FROM node:20-alpine

WORKDIR /app

# نسخ ملفات التبعيات وتثبيتها
COPY package*.json ./
RUN npm install --production

# نسخ باقي ملفات المشروع
COPY . .

# المنفذ
EXPOSE 3000

# أمر التشغيل
CMD ["npm", "start"]
`;
  }

  if (lower === 'docker-compose.yml' || lower === 'docker-compose.yaml') {
    return `version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
`;
  }

  if (lower.endsWith('.md')) {
    return `# توثيق المشروع (${fileName})

## نظرة عامة
تم إنشاء هذا المشروع عبر **استوديو بناء المشاريع والأكواد**.

## التثبيت والتشغيل
\`\`\`bash
npm install
npm run dev
\`\`\`

## الهيكل التنظيمي
- \`src/\`: الشيفرة المصدرية
- \`public/\`: الأصول الثابتة
`;
  }

  return `// ${fileName}\n// يمكنك كتابة الكود هنا...\n`;
}

/**
 * Distinguishes whether an item name is a file or a folder.
 * Folders end with '/' or have no extension (unless known extensionless files like Dockerfile, Makefile, LICENSE, etc.)
 */
export function isFolder(name: string): boolean {
  const clean = name.trim();
  if (clean.endsWith('/')) return true;
  const lower = clean.toLowerCase();
  if (['dockerfile', 'makefile', 'license', 'procfile', '.gitignore', '.env', '.env.example'].includes(lower)) {
    return false;
  }
  return !clean.includes('.');
}

let idCounter = 1;
export function generateUniqueId(): string {
  return `node_${Date.now()}_${idCounter++}_${Math.random().toString(36).substring(2, 7)}`;
}

/**
 * Parses a flat list of file paths (e.g. /src/App.tsx, src/components/Modal.tsx)
 * into a full hierarchical FileNode[] tree.
 */
export function parsePathList(lines: string[], populateDefaultContent = true): FileNode[] {
  const rootNodes: FileNode[] = [];
  const pathToNodeMap = new Map<string, FileNode>();

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) continue;

    // Strip tree branch symbols and bullets if any
    const pathOnly = trimmed.replace(/^(?:[│\|]\s*|\+--\s*|`--\s*|├──\s*|└──\s*|[-*•]\s*)+/, '').trim();
    const cleanPath = pathOnly.replace(/^[\\/]+/, '').replace(/[\\/]+$/, '').replace(/\\/g, '/');
    if (!cleanPath) continue;

    const isExplicitDir = pathOnly.endsWith('/') || (!cleanPath.includes('.') && isFolder(cleanPath));
    const parts = cleanPath.split('/').filter(p => p.trim().length > 0);
    let currentPath = '';
    let parentNode: FileNode | null = null;

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const isLeaf = i === parts.length - 1;
      const isDir = !isLeaf || isExplicitDir;

      let existing = pathToNodeMap.get(currentPath);
      if (!existing) {
        const fileContent = isDir ? undefined : (populateDefaultContent ? getDefaultContentForFile(part, currentPath) : '');
        const newNode: FileNode = {
          id: generateUniqueId(),
          name: part,
          type: isDir ? 'folder' : 'file',
          path: currentPath,
          isOpen: true,
          isSaved: true,
          lastModified: Date.now(),
          content: fileContent,
          size: fileContent ? fileContent.length : 0,
          children: isDir ? [] : undefined,
          parentId: parentNode ? parentNode.id : null
        };

        pathToNodeMap.set(currentPath, newNode);

        if (parentNode) {
          if (!parentNode.children) parentNode.children = [];
          parentNode.children.push(newNode);
        } else {
          rootNodes.push(newNode);
        }

        existing = newNode;
      }

      if (isDir) {
        parentNode = existing;
      }
    }
  }

  updatePaths(rootNodes, '');
  return rootNodes;
}

/**
 * Parse project structure from tree text (ASCII, indented, paths, JSON, YAML)
 */
export function parseTreeFromText(rawText: string, populateDefaultContent = true): FileNode[] {
  let trimmed = rawText.trim();
  if (!trimmed) return [];

  // 1. Check if raw text starts with escaped string or quotes (e.g. \n \n\n"index.html": ...)
  if (trimmed.startsWith('\\n') || (trimmed.startsWith('"') && trimmed.includes('":'))) {
    try {
      const unescaped = trimmed
        .replace(/^["'\s]+/, '')
        .replace(/["'\s]+$/, '')
        .replace(/\\n/g, '\n')
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, '\\');
      if (unescaped.includes('":')) {
        trimmed = unescaped.startsWith('{') ? unescaped : `{${unescaped}}`;
      }
    } catch {}
  }

  // 2. Strip Markdown code blocks if any
  if (trimmed.startsWith('```')) {
    trimmed = trimmed.replace(/^```[a-z]*\s*\n?/i, '').replace(/\n?```\s*$/, '').trim();
  }

  // 3. Try JSON first if it looks like JSON
  if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {
    try {
      const parsed = JSON.parse(trimmed);
      return parseJsonTree(parsed, populateDefaultContent);
    } catch {
      // Fall through to text-based parser
    }
  }

  const lines = trimmed.split('\n');

  // Check if input is a flat path list (e.g. /src/components/AddPaymentModal.tsx or src/App.tsx)
  const hasSlashesInNames = lines.some(l => {
    const { cleanName } = extractNameAndDepth(l);
    return cleanName.replace(/\/$/, '').includes('/');
  });

  if (hasSlashesInNames) {
    return parsePathList(lines, populateDefaultContent);
  }

  const rootNodes: FileNode[] = [];

  // Stack of { node, depth }
  const stack: { node: FileNode; depth: number }[] = [];

  for (const rawLine of lines) {
    if (!rawLine.trim()) continue;

    // Check depth based on indentation and tree branches
    const { cleanName, depth } = extractNameAndDepth(rawLine);
    if (!cleanName) continue;

    const folder = isFolder(cleanName);
    const normalizedName = cleanName.replace(/\/$/, '');

    const newNode: FileNode = {
      id: generateUniqueId(),
      name: normalizedName,
      type: folder ? 'folder' : 'file',
      path: normalizedName, // will be updated recursively
      isOpen: true,
      isSaved: true,
      lastModified: Date.now(),
      children: folder ? [] : undefined,
      content: folder ? undefined : (populateDefaultContent ? getDefaultContentForFile(normalizedName) : ''),
      size: folder ? 0 : (populateDefaultContent ? getDefaultContentForFile(normalizedName).length : 0)
    };

    // Find parent in stack
    while (stack.length > 0 && stack[stack.length - 1].depth >= depth) {
      stack.pop();
    }

    if (stack.length === 0) {
      newNode.parentId = null;
      rootNodes.push(newNode);
    } else {
      const parent = stack[stack.length - 1].node;
      newNode.parentId = parent.id;
      if (!parent.children) parent.children = [];
      parent.children.push(newNode);
    }

    if (folder) {
      stack.push({ node: newNode, depth });
    }
  }

  // Update absolute paths for all nodes
  updatePaths(rootNodes, '');
  return rootNodes;
}

function parseJsonTree(jsonObj: any, populateDefaultContent: boolean): FileNode[] {
  if (Array.isArray(jsonObj)) {
    return jsonObj.map(item => parseJsonNode(item, null, '', populateDefaultContent));
  }
  // If it's a map like { "src": { "App.tsx": "" } }
  return parseObjectMap(jsonObj, null, '', populateDefaultContent);
}

function parseObjectMap(obj: Record<string, any>, parentId: string | null, parentPath: string, populateDefaultContent: boolean): FileNode[] {
  // If keys contain slashes (e.g. "src/App.tsx" or "نظام-حضور/metadata.json"), build real directory structure
  const hasSlashes = Object.keys(obj).some(k => k.includes('/'));
  if (hasSlashes) {
    const rootNodes: FileNode[] = [];
    const pathToNodeMap = new Map<string, FileNode>();

    for (const [rawKey, val] of Object.entries(obj)) {
      const cleanPath = rawKey.replace(/^[\\/]+/, '').replace(/[\\/]+$/, '').replace(/\\/g, '/');
      const parts = cleanPath.split('/').filter(p => p.trim().length > 0);
      let currentPath = '';
      let parentNode: FileNode | null = null;

      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        currentPath = currentPath ? `${currentPath}/${part}` : part;
        const isLeaf = i === parts.length - 1;
        const isDir = !isLeaf || (typeof val === 'object' && val !== null && !Array.isArray(val));

        let existing = pathToNodeMap.get(currentPath);
        if (!existing) {
          const content = isDir ? undefined : (typeof val === 'string' && val ? val : (populateDefaultContent ? getDefaultContentForFile(part) : ''));
          const newNode: FileNode = {
            id: generateUniqueId(),
            name: part,
            type: isDir ? 'folder' : 'file',
            path: currentPath,
            parentId: parentNode ? parentNode.id : null,
            isOpen: true,
            isSaved: true,
            lastModified: Date.now(),
            children: isDir ? [] : undefined,
            content: isDir ? undefined : content,
            size: content ? content.length : 0
          };
          pathToNodeMap.set(currentPath, newNode);

          if (parentNode) {
            if (!parentNode.children) parentNode.children = [];
            parentNode.children.push(newNode);
          } else {
            rootNodes.push(newNode);
          }
          existing = newNode;
        }
        if (isDir) {
          parentNode = existing;
        }
      }
    }
    updatePaths(rootNodes, '');
    return rootNodes;
  }

  const result: FileNode[] = [];
  for (const [key, val] of Object.entries(obj)) {
    const isDir = typeof val === 'object' && val !== null && !Array.isArray(val);
    const currentPath = parentPath ? `${parentPath}/${key}` : key;
    const node: FileNode = {
      id: generateUniqueId(),
      name: key,
      type: isDir ? 'folder' : 'file',
      path: currentPath,
      parentId,
      isOpen: true,
      isSaved: true,
      lastModified: Date.now(),
      children: isDir ? parseObjectMap(val, '', currentPath, populateDefaultContent) : undefined,
      content: isDir ? undefined : (typeof val === 'string' && val ? val : (populateDefaultContent ? getDefaultContentForFile(key) : '')),
      size: 0
    };
    if (node.children) {
      node.children.forEach(child => { child.parentId = node.id; });
    }
    if (node.content) {
      node.size = node.content.length;
    }
    result.push(node);
  }
  return result;
}

function parseJsonNode(raw: any, parentId: string | null, parentPath: string, populateDefaultContent: boolean): FileNode {
  const name = raw.name || 'unnamed';
  const type: 'file' | 'folder' = raw.type === 'folder' || raw.children ? 'folder' : 'file';
  const currentPath = parentPath ? `${parentPath}/${name}` : name;
  const content = type === 'file' ? (raw.content ?? (populateDefaultContent ? getDefaultContentForFile(name) : '')) : undefined;

  const node: FileNode = {
    id: raw.id || generateUniqueId(),
    name,
    type,
    path: currentPath,
    parentId,
    isOpen: true,
    isSaved: true,
    lastModified: Date.now(),
    content,
    size: content ? content.length : 0,
    children: type === 'folder' ? [] : undefined
  };

  if (Array.isArray(raw.children) && type === 'folder') {
    node.children = raw.children.map((child: any) => parseJsonNode(child, node.id, currentPath, populateDefaultContent));
  }

  return node;
}

function extractNameAndDepth(line: string): { cleanName: string; depth: number } {
  // Strip tree symbols like ├──, └──, │, |-, `--, +--
  let depth = 0;
  let cursor = 0;

  // Measure leading spaces or tabs
  while (cursor < line.length && (line[cursor] === ' ' || line[cursor] === '\t')) {
    if (line[cursor] === '\t') depth += 4;
    else depth += 1;
    cursor++;
  }

  const remainder = line.substring(cursor);

  // Match tree branches
  const branchMatch = remainder.match(/^(?:[│\|]\s*|\+--\s*|`--\s*|├──\s*|└──\s*)+/);
  if (branchMatch) {
    depth += branchMatch[0].length * 2;
  }

  let cleanName = remainder.replace(/^(?:[│\|]\s*|\+--\s*|`--\s*|├──\s*|└──\s*)+/, '').trim();
  
  // Remove leading slashes if any
  cleanName = cleanName.replace(/^\.?\//, '');

  return { cleanName, depth };
}

export function updatePaths(nodes: FileNode[], parentPath = ''): void {
  for (const node of nodes) {
    node.path = parentPath ? `${parentPath}/${node.name}` : node.name;
    if (node.children && node.children.length > 0) {
      updatePaths(node.children, node.path);
    }
  }
}

export function getAllFiles(nodes: FileNode[]): FileNode[] {
  const files: FileNode[] = [];
  function traverse(list: FileNode[]) {
    for (const node of list) {
      if (node.type === 'file') {
        files.push(node);
      } else if (node.children) {
        traverse(node.children);
      }
    }
  }
  traverse(nodes);
  return files;
}

export function getAllFolders(nodes: FileNode[]): FileNode[] {
  const folders: FileNode[] = [];
  function traverse(list: FileNode[]) {
    for (const node of list) {
      if (node.type === 'folder') {
        folders.push(node);
        if (node.children) traverse(node.children);
      }
    }
  }
  traverse(nodes);
  return folders;
}

export function findNodeById(nodes: FileNode[], id: string): FileNode | null {
  for (const node of nodes) {
    if (node.id === id) return node;
    if (node.children) {
      const found = findNodeById(node.children, id);
      if (found) return found;
    }
  }
  return null;
}

export function findNodeByPath(nodes: FileNode[], targetPath: string): FileNode | null {
  const cleanTarget = targetPath.replace(/^\//, '').toLowerCase();
  for (const node of nodes) {
    if (node.path.toLowerCase() === cleanTarget) return node;
    if (node.children) {
      const found = findNodeByPath(node.children, targetPath);
      if (found) return found;
    }
  }
  return null;
}

export function updateNodeContent(
  nodes: FileNode[],
  id: string,
  content: string,
  markSaved = false
): FileNode[] {
  return nodes.map(node => {
    if (node.id === id) {
      return {
        ...node,
        content,
        size: new Blob([content]).size,
        lastModified: Date.now(),
        isSaved: markSaved ? true : false
      };
    }
    if (node.children) {
      return {
        ...node,
        children: updateNodeContent(node.children, id, content, markSaved)
      };
    }
    return node;
  });
}

export function markFileSaved(nodes: FileNode[], id: string): FileNode[] {
  return nodes.map(node => {
    if (node.id === id) {
      return { ...node, isSaved: true, lastModified: Date.now() };
    }
    if (node.children) {
      return { ...node, children: markFileSaved(node.children, id) };
    }
    return node;
  });
}

export function addNode(
  nodes: FileNode[],
  targetParentId: string | null,
  newNode: FileNode
): FileNode[] {
  if (targetParentId === null) {
    newNode.parentId = null;
    const updated = [...nodes, newNode];
    updatePaths(updated);
    return updated;
  }

  const result = nodes.map(node => {
    if (node.id === targetParentId && node.type === 'folder') {
      newNode.parentId = node.id;
      const children = node.children ? [...node.children, newNode] : [newNode];
      return { ...node, children, isOpen: true };
    }
    if (node.children) {
      return {
        ...node,
        children: addNode(node.children, targetParentId, newNode)
      };
    }
    return node;
  });

  updatePaths(result);
  return result;
}

export function removeNode(nodes: FileNode[], id: string): FileNode[] {
  return nodes
    .filter(node => node.id !== id)
    .map(node => {
      if (node.children) {
        return {
          ...node,
          children: removeNode(node.children, id)
        };
      }
      return node;
    });
}

export function renameNode(nodes: FileNode[], id: string, newName: string): FileNode[] {
  const result: FileNode[] = nodes.map(node => {
    if (node.id === id) {
      const isDir = node.type === 'folder';
      const nodeType: 'file' | 'folder' = isDir ? 'folder' : (isFolder(newName) ? 'folder' : 'file');
      return {
        ...node,
        name: newName,
        type: nodeType
      };
    }
    if (node.children) {
      return {
        ...node,
        children: renameNode(node.children, id, newName)
      };
    }
    return node;
  });

  updatePaths(result);
  return result;
}

export function moveNode(
  nodes: FileNode[],
  sourceId: string,
  targetFolderId: string | null
): FileNode[] {
  const nodeToMove = findNodeById(nodes, sourceId);
  if (!nodeToMove) return nodes;

  // Avoid moving folder into itself or its own descendants
  if (nodeToMove.type === 'folder' && targetFolderId) {
    const targetNode = findNodeById(nodes, targetFolderId);
    if (targetNode && targetNode.path.startsWith(nodeToMove.path)) {
      return nodes; // invalid move
    }
  }

  // First remove
  const withoutSource = removeNode(nodes, sourceId);

  // Then add to new parent
  const movedNodeCopy: FileNode = {
    ...nodeToMove,
    parentId: targetFolderId
  };

  return addNode(withoutSource, targetFolderId, movedNodeCopy);
}

export function toggleFolderOpen(nodes: FileNode[], id: string): FileNode[] {
  return nodes.map(node => {
    if (node.id === id) {
      return { ...node, isOpen: !node.isOpen };
    }
    if (node.children) {
      return { ...node, children: toggleFolderOpen(node.children, id) };
    }
    return node;
  });
}

export function setAllFoldersOpen(nodes: FileNode[], isOpen: boolean): FileNode[] {
  return nodes.map(node => {
    if (node.type === 'folder') {
      return {
        ...node,
        isOpen,
        children: node.children ? setAllFoldersOpen(node.children, isOpen) : undefined
      };
    }
    return node;
  });
}

export function serializeTreeToText(nodes: FileNode[], prefix = ''): string {
  let result = '';
  nodes.forEach((node, index) => {
    const isLast = index === nodes.length - 1;
    const branch = isLast ? '└── ' : '├── ';
    result += `${prefix}${branch}${node.name}${node.type === 'folder' ? '/' : ''}\n`;
    if (node.children && node.children.length > 0) {
      const childPrefix = prefix + (isLast ? '    ' : '│   ');
      result += serializeTreeToText(node.children, childPrefix);
    }
  });
  return result;
}

export function calculateTotalSize(nodes: FileNode[]): number {
  let total = 0;
  function traverse(list: FileNode[]) {
    for (const node of list) {
      if (node.type === 'file' && node.size) {
        total += node.size;
      }
      if (node.children) traverse(node.children);
    }
  }
  traverse(nodes);
  return total;
}

export function countUnsavedFiles(nodes: FileNode[]): number {
  let count = 0;
  function traverse(list: FileNode[]) {
    for (const node of list) {
      if (node.type === 'file' && node.isSaved === false) {
        count++;
      }
      if (node.children) traverse(node.children);
    }
  }
  traverse(nodes);
  return count;
}
